### ISSUE TITLE
About renderings that needed in video and slides

### ISSUE THREAD

**Issue by Wuuw12** [Wuuw12/DataScience-G9#8]
Hey guys can you tell me what renderings do you need in our video and slides? like what subject or perspective

**Comment by WANG-yingxuan** [comment]
I think we need to talk about the background and significance of this website, to explain why we want Mark to be the protagonist, to take us all on the journey to Scotland, to understand the stories of these bricks and their factories.

**Comment by WANG-yingxuan** [comment]
I think it's good that our video presents a retro style, because this website is all about the history of Scottish brick and tile.
I drew some pictures to express it. I think it can be put in the video and PPT.
![jfy](https://user-images.githubusercontent.com/72726322/101240881-057bfd80-372d-11eb-8fbc-f5aebdc0b11c.png
<img width="1166" alt="1" src="https://user-images.githubusercontent.com/72726322/101240907-35c39c00-372d-11eb-8bdc-c65eb5fad41a.png">
)
<img width="1161" alt="2" src="https://user-images.githubusercontent.com/72726322/101240917-4f64e380-372d-11eb-80ce-549f6ee52788.png">

**Comment by WANG-yingxuan** [comment]
I think it's good that our video presents a retro style, because this website is all about the history of Scottish brick and tile.
I've done some animations about Mark and put them on the main branches. You can go there and have a look. I hope it will inspire you
